using GrowDiary.Web.Api.Contracts;
using GrowDiary.Web.Models;

namespace GrowDiary.Web.Api.Mapping;

public static class GrowMapping
{
    public static GrowSummaryDto ToSummaryDto(this GrowRun grow) => new(
        Id: grow.Id,
        Name: grow.Name,
        Strain: grow.Strain,
        Breeder: grow.Breeder,
        Status: grow.Status,
        HydroStyle: grow.HydroStyle,
        Environment: grow.Environment,
        SeedType: grow.SeedType,
        StartMaterial: grow.StartMaterial,
        PlantCount: grow.PlantCount,
        TentId: grow.TentId,
        TentName: grow.TentName,
        StartDate: grow.StartDate,
        EndDate: grow.EndDate,
        FlipDate: grow.FlipDate,
        GerminatedAt: grow.GerminatedAt,
        RootedAt: grow.RootedAt,
        MeasurementCount: grow.MeasurementCount,
        LatestPhotoPath: grow.LatestPhotoPath,
        LatestStage: grow.LatestMeasurement?.Stage,
        LatestReservoirPh: grow.LatestMeasurement?.ReservoirPh,
        LatestReservoirEc: grow.LatestMeasurement?.ReservoirEc,
        LatestMeasurementAt: grow.LatestMeasurement?.TakenAt
    );

    public static GrowDetailDto ToDetailDto(this GrowRun grow) => new(
        Id: grow.Id,
        SystemId: grow.SystemId,
        Name: grow.Name,
        Strain: grow.Strain,
        Breeder: grow.Breeder,
        Status: grow.Status,
        MediumType: grow.MediumType,
        FeedingStyle: grow.FeedingStyle,
        HydroStyle: grow.HydroStyle,
        IrrigationType: grow.IrrigationType,
        WaterSource: grow.WaterSource,
        Environment: grow.Environment,
        Light: grow.Light,
        ContainerSize: grow.ContainerSize,
        ReservoirSize: grow.ReservoirSize,
        MediumDetail: grow.MediumDetail,
        IrrigationStyle: grow.IrrigationStyle,
        HasChiller: grow.HasChiller,
        SeedType: grow.SeedType,
        StartMaterial: grow.StartMaterial,
        GerminationMethod: grow.GerminationMethod,
        PropagationMedium: grow.PropagationMedium,
        CloneSource: grow.CloneSource,
        CloneIsRooted: grow.CloneIsRooted,
        BreederFlowerWeeksMin: grow.BreederFlowerWeeksMin,
        BreederFlowerWeeksMax: grow.BreederFlowerWeeksMax,
        PlantCount: grow.PlantCount,
        PhenoNumber: grow.PhenoNumber,
        TentId: grow.TentId,
        TentName: grow.TentName,
        EntryPoint: grow.EntryPoint,
        DaysAlreadyInPhase: grow.DaysAlreadyInPhase,
        AutoflowerDaysSinceGermination: grow.AutoflowerDaysSinceGermination,
        StartDate: grow.StartDate,
        EndDate: grow.EndDate,
        FlipDate: grow.FlipDate,
        GerminatedAt: grow.GerminatedAt,
        RootedAt: grow.RootedAt,
        Nutrients: grow.Nutrients,
        Notes: grow.Notes,
        MeasurementCount: grow.MeasurementCount,
        LatestPhotoPath: grow.LatestPhotoPath,
        LatestMeasurement: grow.LatestMeasurement?.ToDto(),
        CreatedAtUtc: grow.CreatedAtUtc,
        UpdatedAtUtc: grow.UpdatedAtUtc
    );
}
